### PR TITLE
Tests for when arrow function returns object literal.

### LINKED ISSUE #43: ES6 arrow functions
Source: `logs.map(l => {return {a: l.name, b: l.id}})`
Minified: `logs.map(l => {a: l.name, b: l.id})`

### PR DESCRIPTION
**Pull request by samjudson**
Hi

I've made a small change to see if I could get it to handle arrow functions that return object literals.

Not sure if I've done this correctly, so let me know if this should be handled some other way.

Should fix #43 (as well as https://github.com/madskristensen/BundlerMinifier/issues/301)

### CODE REVIEW

**Comment by xoofx** [comment]
Thanks!

**Comment by rockstardev** [comment]
OK @xoofx I'll give it a try of publishing new version ;) Will just wait on @samjudson to finish with changes and then tag.

**Comment by samjudson** [comment]
Haven't got any more changes I can think of.

**Comment by rockstardev** [comment]
@samjudson OK man, if you are done - I'll proceed with making changelog and publishing new version. I have really busy day ahead of me today, so maybe only get to doing this tomorrow - will update you as soon as it's done.

**Pull request merged**
